### PR TITLE
Release/8.5.1

### PR DESCRIPTION
**Pull request by PierreJeanjacquot**
### Changed

- fix regression causing browser providers (metamask) to prompt unlock screen on IExec instantiation
- fix `iexec task show --download` issue with node 18 and above

### CODE REVIEW

**Review by Le-Caignec — APPROVED** [review]
no package-lock.json updated with the new version ?

**Comment by PierreJeanjacquot** [comment]
> no package-lock.json updated with the new version in the file change ?

actually yes

**Comment by PierreJeanjacquot** [comment]
@Le-Caignec added the second fix in the PR

**Review by Le-Caignec — APPROVED** [review]
LGTM

**Pull request merged**
